version: '3.9'

services:
  db:
    image: postgres:14.3
    container_name: bancalite-db
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-bancalite}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME:-bancalite}"]
      interval: 5s
      timeout: 5s
      retries: 10

# Nota: más adelante puedes añadir 'api' y 'web' aquí.
