name: CI • Test, Build and (on main) Push Docker image

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: .NET Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore bancalite-backend/Bancalite.sln

      - name: Run tests (Release)
        run: dotnet test bancalite-backend/tests/Tests.Unit/Tests.Unit.csproj --configuration Release --nologo --no-restore

  docker:
    name: Docker Build (and Push on main)
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}-app
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/bancalite-app
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/bancalite-api # alias temporal de compatibilidad
          tags: |
            # Always tag with short SHA
            type=sha,format=short
            # Branch tags (e.g., main)
            type=ref,event=branch
            # Tag from annotated/semver tags (e.g., v1.2.3)
            type=ref,event=tag
            # Additional semver tags: 1.2.3, 1.2, 1 (only when pushing a semver tag)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            # Stable aliases for main
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
            type=raw,value=app,enable=${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

      - name: Login to GHCR
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (and push on main)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: bancalite-backend/src/Bancalite.WebApi/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
